In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(
    columns=["Name", "Age", "Height"],
)

df

Empty DataFrame
Columns: [Name, Age, Height]
Index: []

In [3]:
print(df)

Empty DataFrame
Columns: [Name, Age, Height]
Index: []

In [4]:
df.loc[0] = ["Allen", 22, 175]

df

    Name  Age  Height
0  Allen   22     175

In [5]:
df.loc[1] = ["Jack", 25, 180]
df

    Name  Age  Height
0  Allen   22     175
1   Jack   25     180

In [8]:
df["Age"][1] = 28

/var/folders/_k/k5dry95j0q5d35_9pn5d86vm0000gn/T/ipykernel_50320/2063534485.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df["Age"][1] = 28

In [11]:
df.loc[1, "Age"] = 28

In [12]:
df

    Name  Age  Height
0  Allen   22     175
1   Jack   28     180

In [14]:
df["Weight"] = [75, 80]

In [15]:
df

    Name  Age  Height  Weight
0  Allen   22     175      75
1   Jack   28     180      80

In [17]:
df.drop("Weight", axis=1)

    Name  Age  Height
0  Allen   22     175
1   Jack   28     180

In [19]:
df = df.drop("Weight", axis=1)
df

    Name  Age  Height
0  Allen   22     175
1   Jack   28     180

In [20]:
df.drop(1)

    Name  Age  Height
0  Allen   22     175

In [21]:
df

    Name  Age  Height
0  Allen   22     175
1   Jack   28     180

In [22]:
df = df.drop(1)
df

    Name  Age  Height
0  Allen   22     175

In [23]:
df["Age"]

0    22
Name: Age, dtype: int64

In [26]:
"""
select
    age + 10
from user
"""
df["Age"] + 10

0    32
Name: Age, dtype: int64

In [27]:
df

    Name  Age  Height
0  Allen   22     175

In [28]:
df["Age"] = df["Age"] + 10
df

    Name  Age  Height
0  Allen   32     175

In [31]:
df2 = df

In [30]:
df2[0, "Age"] = 50
df2

    Name  Age  Height  (0, Age)
0  Allen   32     175        50

In [32]:
df

    Name  Age  Height  (0, Age)
0  Allen   32     175        50

In [33]:
df3 = df.copy()

In [34]:
df3.loc[0, "Age"] = 5
df3

    Name  Age  Height  (0, Age)
0  Allen    5     175        50

In [35]:
df

    Name  Age  Height  (0, Age)
0  Allen   32     175        50

In [38]:
df

    Name  Age  Height  (0, Age)
0  Allen   32     175        50

In [37]:
df.loc[:, "Age"]

0    32
Name: Age, dtype: int64

In [39]:
df.loc[:, ["Age", "Name"]]

   Age   Name
0   32  Allen

In [41]:
df

    Name  Age  Height  (0, Age)
0  Allen   32     175        50

In [42]:
df.iloc[:, [0, 1]]

    Name  Age
0  Allen   32

In [43]:
data = [
    ["Allen", 22, 170],
    ["Ted", 25, 180],
]

pd.DataFrame(data=data)

       0   1    2
0  Allen  22  170
1    Ted  25  180