In [2]:
import pandas as pd

In [3]:
df = pd.read_parquet("holding.parquet")

In [4]:
df

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
13461477,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,2.229475e+04,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
13461478,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148050e+04,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
13461479,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148400e+04,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
13461480,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,1.918738e+04,Endo DAC 6% 30-JUN-2028,29273DAC
13461481,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,1.497188e+04,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [5]:
"""
select distinct(portno) from df;
select count(distinct(portno)) from df;
"""
df["portno"].unique()

<ArrowStringArray>
['2998623', '2998638', '2998809', '2998821', '3000255', '300035d', '3001404',
 '3002313', '3002316', '300251d',
 ...
 '3156837', '3156924', '3157206', '3157233', '315723c', '3157245', '315724b',
 '315724e', '3157332', '3157350']
Length: 9453, dtype: str

In [6]:
"""
select * from df limit 8;
"""
df.head(8)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08,GOLDMAN SACHS GROUP INC,38141G10
6,2998623,2020/11/30,7,2021/01/08,1.63,2194727.0,1.976352e+08,C S X CORP,12640810
7,2998623,2020/11/30,8,2021/01/08,1.60,5045923.0,1.939653e+08,AMERICAN INTERNATIONAL GROUP INC,02687478

In [7]:
df.tail()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
13461477,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,22294.75,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
13461478,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,21480.50,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
13461479,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,21484.00,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
13461480,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,19187.38,Endo DAC 6% 30-JUN-2028,29273DAC
13461481,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,14971.88,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [8]:
df[3:9]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08,GOLDMAN SACHS GROUP INC,38141G10
6,2998623,2020/11/30,7,2021/01/08,1.63,2194727.0,1.976352e+08,C S X CORP,12640810
7,2998623,2020/11/30,8,2021/01/08,1.60,5045923.0,1.939653e+08,AMERICAN INTERNATIONAL GROUP INC,02687478
8,2998623,2020/11/30,9,2021/01/08,1.59,1403360.0,1.937619e+08,P N C FINANCIAL SERVICES GRP INC,69347510

In [9]:
df.loc[:, "report_dt":"nbr_shares"]

           report_dt  security_rank      eff_dt  percent_tna  nbr_shares
0         2020/11/30              1  2021/01/08         2.55   7078982.0
1         2020/11/30              2  2021/01/08         1.98   3087680.0
2         2020/11/30              3  2021/01/08         1.89   3714760.0
3         2020/11/30              4  2021/01/08         1.75   2815186.0
4         2020/11/30              5  2021/01/08         1.65   5248941.0
...              ...            ...         ...          ...         ...
13461477  2021/11/30            428  2021/12/21         0.11     25000.0
13461478  2021/11/30            429  2021/12/21         0.11     25000.0
13461479  2021/11/30            429  2021/12/21         0.11     25000.0
13461480  2021/11/30            431  2021/12/21         0.10     25000.0
13461481  2021/11/30            432  2021/12/21         0.08     25000.0

[13461482 rows x 5 columns]

In [10]:
df.columns

Index(['portno', 'report_dt', 'security_rank', 'eff_dt', 'percent_tna',
       'nbr_shares', 'market_val', 'security_name', 'cusip'],
      dtype='str')

In [11]:
df.dtypes

portno               str
report_dt            str
security_rank      int64
eff_dt               str
percent_tna      float64
nbr_shares       float64
market_val       float64
security_name        str
cusip                str
dtype: object

In [12]:
df["cusip"].dtype

In [13]:
df["nbr_shares"].mean()

np.float64(24384357.812074553)

In [14]:
df["nbr_shares"].std()

np.float64(6523190968.803617)

In [15]:
df.mean()

TypeError: Cannot perform reduction 'mean' with string dtype

In [16]:
df[["percent_tna", "nbr_shares"]].mean()

percent_tna    4.404682e-01
nbr_shares     2.438436e+07
dtype: float64

In [17]:
df["portno"].value_counts()

portno
3062436    58487
314420d    44636
309585f    43616
314834d    38124
3101229    34556
           ...
3079800        1
309254a        1
3092553        1
3155640        1
3156639        1
Name: count, Length: 9453, dtype: int64

In [18]:
df.describe()

       security_rank   percent_tna    nbr_shares    market_val
count   1.346148e+07  1.346148e+07  1.346148e+07  1.346148e+07
mean    5.865976e+02  4.404682e-01  2.438436e+07  1.137428e+07
std     8.539445e+02  2.125681e+00  6.523191e+09  1.651424e+08
min     1.000000e+00 -2.489000e+02 -1.027540e+12 -6.520285e+09
25%     8.200000e+01  2.000000e-02  5.744000e+03  1.153754e+05
50%     2.750000e+02  8.000000e-02  5.249300e+04  6.464532e+05
75%     7.270000e+02  3.100000e-01  4.488590e+05  3.176073e+06
max     8.716000e+03  3.028200e+02  6.667220e+12  7.118158e+10

In [19]:
df.head()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10

In [20]:
"""
select * fomr df
where portno = '2998623'
"""
df[df["portno"] == "2998623"]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
12163648,2998623,2021/10/31,339,2021/12/07,0.00,5.0,5.650000e+00,Freddie Mac 01-FEB-2037 A57210,3128KLAK
12163649,2998623,2021/10/31,339,2021/12/07,0.00,678.0,8.030000e+02,Ginnie Mae 2 20-DEC-2030 003011,36202DKY
12163650,2998623,2021/10/31,339,2021/12/07,0.00,1021.0,1.223010e+03,Ginnie Mae 2 20-JAN-2031 003028,36202DLH
12163651,2998623,2021/10/31,339,2021/12/07,0.00,3164.0,3.177910e+03,Gvt Ntl Mrtg Asn 15-JUN-2026 422949,36206VZN
12163652,2998623,2021/10/31,339,2021/12/07,0.00,5140.0,5.159240e+03,Fannie Mae 01-JUL-2032 642656,31390C5R

In [21]:
df["portno"] == "2998623"

0            True
1            True
2            True
3            True
4            True
            ...
13461477    False
13461478    False
13461479    False
13461480    False
13461481    False
Name: portno, Length: 13461482, dtype: bool

In [22]:
filter_portno_2998623 = df["portno"] == "2998623"
filter_percent_tna_gt_2 = df["percent_tna"] > 2

In [23]:
"""
select * from df
where portno = '2998623'
and percent_tna > 2
"""

df[
    filter_portno_2998623
    & filter_percent_tna_gt_2
]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1278784,2998623,2020/12/31,1,2021/02/05,2.30,6810121.0,2.835734e+08,GENERAL MOTORS CO,37045V10
4209370,2998623,2021/03/31,1,2021/05/10,3.14,409035800.0,4.055047e+08,United States of America .5% 31-MAR-2026,91282CBT
4209371,2998623,2021/03/31,2,2021/05/10,2.56,5754696.0,3.306648e+08,GENERAL MOTORS CO,37045V10
4209372,2998623,2021/03/31,3,2021/05/10,2.52,325776946.0,3.257769e+08,Invesco Treasury Portfolio;Institutional,82525240
4209373,2998623,2021/03/31,4,2021/05/10,2.38,7937277.0,3.070932e+08,BANK OF AMERICA CORP,06050510
4209374,2998623,2021/03/31,5,2021/05/10,2.21,285054828.0,2.850548e+08,Invesco Government & Agency Portfolio;Inst,82525288
4209375,2998623,2021/03/31,6,2021/05/10,2.04,6760345.0,2.641267e+08,WELLS FARGO & CO NEW,94974610
5308053,2998623,2021/04/30,1,2021/06/07,3.34,445035800.0,4.433321e+08,United States of America .5% 31-MAR-2026,91282CBT
5308054,2998623,2021/04/30,2,2021/06/07,2.48,5754696.0,3.292837e+08,GENERAL MOTORS CO,37045V10
5308055,2998623,2021/04/30,3,2021/06/07,2.42,7937277.0,3.216978e+08,BANK OF AMERICA CORP,06050510
5308056,2998623,2021/04/30,4,2021/06/07,2.29,6760345.0,3.045535e+08,WELLS FARGO & CO NEW,94974610
7493123,2998623,2021/06/30,1,2021/08/09,4.04,535535800.0,5.353057e+08,United States of America (Government) .375% 30...,91282CCJ
7493124,2998623,2021/06/30,2,2021/08/09,2.39,7705229.0,3.176866e+08,BANK OF AMERICA CORP,06050510
7493125,2998623,2021/06/30,3,2021/08/09,2.36,5299484.0,3.135705e+08,GENERAL MOTORS CO,37045V10
7493126,2998623,2021/06/30,4,2021/08/09,2.24,6562706.0,2.972250e+08,WELLS FARGO & CO NEW,94974610
8564814,2998623,2021/07/31,1,2021/09/07,4.10,535535800.0,5.404309e+08,United States of America (Government) .375% 30...,91282CCJ
8564815,2998623,2021/07/31,2,2021/09/07,2.36,6772596.0,3.111331e+08,WELLS FARGO & CO NEW,94974610
8564816,2998623,2021/07/31,3,2021/09/07,2.26,5243190.0,2.980229e+08,GENERAL MOTORS CO,37045V10
8564817,2998623,2021/07/31,4,2021/09/07,2.23,7640712.0,2.930977e+08,BANK OF AMERICA CORP,06050510
9776371,2998623,2021/08/31,1,2021/10/07,4.03,535535800.0,5.349501e+08,United States of America (Government) .25% 31-...,91282CCW
9776372,2998623,2021/08/31,2,2021/10/07,2.42,7031765.0,3.213517e+08,WELLS FARGO & CO NEW,94974610
9776373,2998623,2021/08/31,3,2021/10/07,2.19,6938888.0,2.896986e+08,BANK OF AMERICA CORP,06050510
10924362,2998623,2021/09/30,1,2021/11/05,4.09,535535800.0,5.298876e+08,United States of America (Government) .25% 31-...,91282CCW
10924363,2998623,2021/09/30,2,2021/11/05,2.55,7118899.0,3.303881e+08,WELLS FARGO & CO NEW,94974610
10924364,2998623,2021/09/30,3,2021/11/05,2.17,5331344.0,2.810151e+08,GENERAL MOTORS CO,37045V10
10924365,2998623,2021/09/30,4,2021/11/05,2.05,6254400.0,2.654993e+08,BANK OF AMERICA CORP,06050510
12163315,2998623,2021/10/31,1,2021/12/07,3.95,535535800.0,5.277747e+08,United States of America (Government) .375% 30...,91282CCZ
12163316,2998623,2021/10/31,2,2021/12/07,2.70,7044671.0,3.604054e+08,WELLS FARGO & CO NEW,94974610
12163317,2998623,2021/10/31,3,2021/12/07,2.21,6189187.0,2.957194e+08,BANK OF AMERICA CORP,06050510
12163318,2998623,2021/10/31,4,2021/12/07,2.17,5320069.0,2.895714e+08,GENERAL MOTORS CO,37045V10

In [24]:
"""
select * from df
where portno = '2998623'
or percent_tna > 2
"""

df[
    filter_portno_2998623
    | filter_percent_tna_gt_2
]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
13460505,315724e,2021/11/30,10,2021/12/21,2.10,108.0,1.643533e+05,SHOPIFY INC,82509L10
13460506,315724e,2021/11/30,11,2021/12/21,2.08,3237.0,1.627240e+05,VERIZON COMMUNICATIONS INC,92343V10
13460507,315724e,2021/11/30,12,2021/12/21,2.05,248.0,1.606296e+05,SERVICENOW INC,81762P10
13460508,315724e,2021/11/30,13,2021/12/21,2.02,2600.0,1.580219e+05,Recruit Holdings Co Ltd ORD,J6433A10
13461054,3157350,2021/11/30,1,2021/12/21,2.80,553453.0,5.534534e+05,State Street US Government Money Market Fund;Prem,85749270

In [25]:
filter_portno_2998623 = df["portno"] == "2998623"
filter_percent_tna_gt_2 = df["percent_tna"] > 2
filter_rank_gte_2 = df["security_rank"] >= 2
filter_rank_lte_4 = df["security_rank"] <= 4

In [26]:
"""
select *
from df
where (security_rank >= 2 and security_rank <= 4)
or (portno = '2998623' and percent_tna > 2)
"""
df[
    (filter_rank_gte_2 & filter_rank_lte_4)
    | (filter_portno_2998623 & filter_percent_tna_gt_2)
]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
352,2998638,2020/11/30,2,2021/01/08,3.46,10415081.0,2.932887e+08,BANK OF AMERICA CORP,06050510
...,...,...,...,...,...,...,...,...,...
13460550,3157332,2021/11/30,3,2021/12/21,0.31,4773161.0,9.159696e+07,FORD MOTOR CO DEL,34537086
13460551,3157332,2021/11/30,4,2021/12/21,0.30,2156503.0,9.070252e+07,DEVON ENERGY CORP NEW,25179M10
13461055,3157350,2021/11/30,2,2021/12/21,1.76,348026.0,3.480258e+05,USD Cash,NaN
13461056,3157350,2021/11/30,3,2021/12/21,1.24,250000.0,2.452225e+05,CSC Holdings LLC 5.75% 15-JAN-2030,126307BA
13461057,3157350,2021/11/30,4,2021/12/21,1.06,200000.0,2.094200e+05,Ford Motor Credit Company LLC 4.134% 04-AUG-2025,345397XL

## groupby

In [27]:
df.groupby("portno")

In [ ]:
"""
select count(1)
from df
group by portno;
"""
df.groupby("portno").size()

portno
2998623    3114
2998638     853
2998809     276
2998821     629
2998923     385
           ...
3157308     241
315732c      32
3157332     506
315733b      16
3157350     428
Length: 9453, dtype: int64

In [ ]:
"""
select
    portno,
    count(1)
from df
group by portno;
"""
df.groupby("portno", as_index=False).size()

       portno  size
0     2998623  3114
1     2998638   853
2     2998809   276
3     2998821   629
4     2998923   385
...       ...   ...
9448  3157308   241
9449  315732c    32
9450  3157332   506
9451  315733b    16
9452  3157350   428

[9453 rows x 2 columns]

In [32]:
"""
select
    portno,
    sum()
from df
group by portno;
"""
df.groupby("portno", as_index=False).sum()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/302020/11/302020/11/302020/11/302020/1...,542168,2021/01/082021/01/082021/01/082021/01/082021/0...,897.90,4.002971e+10,1.164454e+11,GENERAL MOTORS COCOGNIZANT TECHNOLOGY SOLS COR...,37045V1019244610617446447181721022052L1038141G...
1,2998638,2020/11/302020/11/302020/11/302020/11/302020/1...,33639,2021/01/082021/01/082021/01/082021/01/082021/0...,1098.46,3.403148e+09,1.044637e+11,CITIGROUP INCBANK OF AMERICA CORPPHILIP MORRIS...,17296742060505107181721037045V1061744644026874...
2,2998809,2020/11/302020/11/302020/11/302020/11/302020/1...,9713,2021/01/082021/01/082021/01/082021/01/082021/0...,399.51,1.017395e+09,1.313242e+10,JPMORGAN CHASE & COState Street US Government ...,46625H1085749270369604100605051084265V10247361...
3,2998821,2020/11/302020/11/302020/11/302020/11/302020/1...,16809,2021/01/082021/01/082021/01/082021/01/082021/0...,1200.38,9.877622e+08,2.259974e+10,SCIENCE APPLICATIONS INTL CORPPARSLEY ENERGY I...,808625107018771029261A10G515021087603010497266...
4,2998923,2020/11/302020/11/302020/11/302020/11/302020/1...,6932,2021/01/222021/01/222021/01/222021/01/222021/0...,1099.84,1.723861e+08,4.898485e+09,NEXTERA ENERGY INCAllspring Govt Money Market ...,65339F109499211292826C8325746U1020030N10025537...
...,...,...,...,...,...,...,...,...,...
9448,3157308,2021/11/302021/11/302021/11/302021/11/302021/1...,29151,2021/12/072021/12/072021/12/072021/12/072021/1...,100.23,2.708380e+05,1.954029e+06,USD CashMICROSOFT CORPAPPLE COMPUTER INCALPHAB...,594918100378331002079K30F869211088160R10H0010V...
9449,315732c,2021/11/302021/11/302021/11/302021/11/302021/1...,529,2021/12/072021/12/072021/12/072021/12/072021/1...,100.12,-6.196600e+04,2.893264e+06,Green Thumb Industries Inc TRSTrulieve Cannabi...,09248U5592971A108101861090041L1044888K2000853E...
9450,3157332,2021/11/302021/11/302021/11/302021/11/302021/1...,128104,2021/12/212021/12/212021/12/212021/12/212021/1...,99.94,3.783357e+08,2.981150e+10,ENPHASE ENERGY INCTESLA MOTORS INCFORD MOTOR C...,29355A1088160R103453708625179M1025674610007903...
9451,315733b,2021/11/302021/11/302021/11/302021/11/302021/1...,137,2021/12/072021/12/072021/12/072021/12/072021/1...,99.73,1.783122e+07,2.601732e+07,United States of America (Government) 3.625% 1...,912810FD912810PV912828Y39128282L9128287D912828...
9452,3157350,2021/11/302021/11/302021/11/302021/11/302021/1...,92037,2021/12/212021/12/212021/12/212021/12/212021/1...,99.55,1.927648e+07,1.964126e+07,State Street US Government Money Market Fund;P...,85749270126307BA345397XL92769XAP02156LAE98954N...

In [ ]:
"""
select
    portno,
    sum(security_rank),
    sum(percent_tna)
from df
group by portno;
"""
df.groupby("portno", as_index=False)[["security_rank", "percent_tna"]].sum()

       portno  security_rank  percent_tna
0     2998623         542168       897.90
1     2998638          33639      1098.46
2     2998809           9713       399.51
3     2998821          16809      1200.38
4     2998923           6932      1099.84
...       ...            ...          ...
9448  3157308          29151       100.23
9449  315732c            529       100.12
9450  3157332         128104        99.94
9451  315733b            137        99.73
9452  3157350          92037        99.55

[9453 rows x 3 columns]

In [36]:
df.groupby(["portno", "eff_dt"])["percent_tna"].sum()

portno   eff_dt
2998623  2021/01/08     99.79
         2021/02/05     99.20
         2021/05/10     99.96
         2021/06/07     99.93
         2021/08/09     99.78
                        ...
3157308  2021/12/07    100.23
315732c  2021/12/07    100.12
3157332  2021/12/21     99.94
315733b  2021/12/07     99.73
3157350  2021/12/21     99.55
Name: percent_tna, Length: 59339, dtype: float64

In [37]:
df.groupby(["portno", "eff_dt"], as_index=False)["percent_tna"].sum()

        portno      eff_dt  percent_tna
0      2998623  2021/01/08        99.79
1      2998623  2021/02/05        99.20
2      2998623  2021/05/10        99.96
3      2998623  2021/06/07        99.93
4      2998623  2021/08/09        99.78
...        ...         ...          ...
59334  3157308  2021/12/07       100.23
59335  315732c  2021/12/07       100.12
59336  3157332  2021/12/21        99.94
59337  315733b  2021/12/07        99.73
59338  3157350  2021/12/21        99.55

[59339 rows x 3 columns]

In [40]:
df.groupby(["portno", "eff_dt"], as_index=False)["percent_tna"].sum().sort_values(["portno", "eff_dt"], ascending=False)

        portno      eff_dt  percent_tna
59338  3157350  2021/12/21        99.55
59337  315733b  2021/12/07        99.73
59336  3157332  2021/12/21        99.94
59335  315732c  2021/12/07       100.12
59334  3157308  2021/12/07       100.23
...        ...         ...          ...
4      2998623  2021/08/09        99.78
3      2998623  2021/06/07        99.93
2      2998623  2021/05/10        99.96
1      2998623  2021/02/05        99.20
0      2998623  2021/01/08        99.79

[59339 rows x 3 columns]

In [ ]:
df.groupby(["portno", "eff_dt"], as_index=False)["percent_tna"].sum().sort_values(["portno", "eff_dt"], ascending=False)
df_t = (
    df
    .groupby(
        [
            "portno",
            "eff_dt",
        ],
        as_index=False,
    )["percent_tna"]
    .sum()
    .sort_values(
        [
            "portno",
            "eff_dt",
        ],
        ascending=False,
    )
)