In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("ptt_gossipping.csv")
df

,推,噓,分數,作者,標題,時間
0,推: 25,噓: 4,分數: 21,作者: Rusnake5566 (魯蛇+56 PTT最強帳號),標題: [問卦] 兩個候選人選前一個月同時陣亡的可能性,時間: Fri Oct 2 13:56:39 2020
1,推: 11,噓: 11,分數: 0,作者: LoveMakeLove (ボケ),標題: [新聞]江啟臣：兩岸是不對稱的戰爭 從募兵改徵兵,時間: Wed Oct 7 18:53:08 2020
2,推: 20,噓: 0,分數: 20,作者: MintSu (Simon),標題: [問卦] 如果川普老婆死於武漢肺炎會怎麼樣？,時間: Fri Oct 2 13:30:55 2020
3,推: 31,噓: 2,分數: 29,作者: seiya2000 (風見),標題: [問卦] 為什麼古代生物體型可以長到這麼大？,時間: Fri Oct 2 12:35:18 2020
4,推: 106,噓: 6,分數: 100,作者: kasumi5566 (霞),標題: [問卦] 支那女生是不是都沒錢修補衣服,時間: Fri Oct 2 13:43:25 2020
...,...,...,...,...,...,...
833,推: 10,噓: 1,分數: 9,作者: lockgolden (鎖金),標題: [問卦] PTT十年後會像無名小站那樣關閉嗎?,時間: Fri Oct 2 14:09:32 2020
834,推: 7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020
835,推: 0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020
836,推: 15,噓: 4,分數: 11,作者: stan0720 (Kimo),標題: [問卦] 認真問 人一天可以走幾公里呀？,時間: Fri Oct 2 14:00:50 2020
837,推: 5,噓: 0,分數: 5,作者: bigtreelife (Tree),標題: [問卦] 叫外送的年輕人都是什麼人,時間: Fri Oct 2 15:29:44 2020

In [3]:
def t_push_str_to_int(input_str: str) -> int:
    """推: 25 -> 25"""
    return int(input_str.split(":")[1].strip())

df["推"].apply(t_push_str_to_int)

0       25
1       11
2       20
3       31
4      106
      ...
833     10
834      7
835      0
836     15
837      5
Name: 推, Length: 838, dtype: int64

In [4]:
df["推"]

0       推: 25
1       推: 11
2       推: 20
3       推: 31
4      推: 106
        ...
833     推: 10
834      推: 7
835      推: 0
836     推: 15
837      推: 5
Name: 推, Length: 838, dtype: str

In [5]:
df["推"] = df["推"].apply(t_push_str_to_int)

In [6]:
df

,推,噓,分數,作者,標題,時間
0,25,噓: 4,分數: 21,作者: Rusnake5566 (魯蛇+56 PTT最強帳號),標題: [問卦] 兩個候選人選前一個月同時陣亡的可能性,時間: Fri Oct 2 13:56:39 2020
1,11,噓: 11,分數: 0,作者: LoveMakeLove (ボケ),標題: [新聞]江啟臣：兩岸是不對稱的戰爭 從募兵改徵兵,時間: Wed Oct 7 18:53:08 2020
2,20,噓: 0,分數: 20,作者: MintSu (Simon),標題: [問卦] 如果川普老婆死於武漢肺炎會怎麼樣？,時間: Fri Oct 2 13:30:55 2020
3,31,噓: 2,分數: 29,作者: seiya2000 (風見),標題: [問卦] 為什麼古代生物體型可以長到這麼大？,時間: Fri Oct 2 12:35:18 2020
4,106,噓: 6,分數: 100,作者: kasumi5566 (霞),標題: [問卦] 支那女生是不是都沒錢修補衣服,時間: Fri Oct 2 13:43:25 2020
...,...,...,...,...,...,...
833,10,噓: 1,分數: 9,作者: lockgolden (鎖金),標題: [問卦] PTT十年後會像無名小站那樣關閉嗎?,時間: Fri Oct 2 14:09:32 2020
834,7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020
835,0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020
836,15,噓: 4,分數: 11,作者: stan0720 (Kimo),標題: [問卦] 認真問 人一天可以走幾公里呀？,時間: Fri Oct 2 14:00:50 2020
837,5,噓: 0,分數: 5,作者: bigtreelife (Tree),標題: [問卦] 叫外送的年輕人都是什麼人,時間: Fri Oct 2 15:29:44 2020

In [7]:
df["噓_t"] = df["噓"].apply(t_push_str_to_int)

In [8]:
df

,推,噓,分數,作者,標題,時間,噓_t
0,25,噓: 4,分數: 21,作者: Rusnake5566 (魯蛇+56 PTT最強帳號),標題: [問卦] 兩個候選人選前一個月同時陣亡的可能性,時間: Fri Oct 2 13:56:39 2020,4
1,11,噓: 11,分數: 0,作者: LoveMakeLove (ボケ),標題: [新聞]江啟臣：兩岸是不對稱的戰爭 從募兵改徵兵,時間: Wed Oct 7 18:53:08 2020,11
2,20,噓: 0,分數: 20,作者: MintSu (Simon),標題: [問卦] 如果川普老婆死於武漢肺炎會怎麼樣？,時間: Fri Oct 2 13:30:55 2020,0
3,31,噓: 2,分數: 29,作者: seiya2000 (風見),標題: [問卦] 為什麼古代生物體型可以長到這麼大？,時間: Fri Oct 2 12:35:18 2020,2
4,106,噓: 6,分數: 100,作者: kasumi5566 (霞),標題: [問卦] 支那女生是不是都沒錢修補衣服,時間: Fri Oct 2 13:43:25 2020,6
...,...,...,...,...,...,...,...
833,10,噓: 1,分數: 9,作者: lockgolden (鎖金),標題: [問卦] PTT十年後會像無名小站那樣關閉嗎?,時間: Fri Oct 2 14:09:32 2020,1
834,7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020,0
835,0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020,0
836,15,噓: 4,分數: 11,作者: stan0720 (Kimo),標題: [問卦] 認真問 人一天可以走幾公里呀？,時間: Fri Oct 2 14:00:50 2020,4
837,5,噓: 0,分數: 5,作者: bigtreelife (Tree),標題: [問卦] 叫外送的年輕人都是什麼人,時間: Fri Oct 2 15:29:44 2020,0

In [ ]:
df["噓"].apply(
    lambda x: int(x.split(":")[1].strip())
)

0       4
1      11
2       0
3       2
4       6
       ..
833     1
834     0
835     0
836     4
837     0
Name: 噓, Length: 838, dtype: int64

In [14]:
df["噓"].str.split(":")

0       [噓,  4]
1      [噓,  11]
2       [噓,  0]
3       [噓,  2]
4       [噓,  6]
         ...
833     [噓,  1]
834     [噓,  0]
835     [噓,  0]
836     [噓,  4]
837     [噓,  0]
Name: 噓, Length: 838, dtype: object

In [12]:
df["噓"].str.split(":").str[1].astype(int)

0       4
1      11
2       0
3       2
4       6
       ..
833     1
834     0
835     0
836     4
837     0
Name: 噓, Length: 838, dtype: int64

In [15]:
df

,推,噓,分數,作者,標題,時間,噓_t
0,25,噓: 4,分數: 21,作者: Rusnake5566 (魯蛇+56 PTT最強帳號),標題: [問卦] 兩個候選人選前一個月同時陣亡的可能性,時間: Fri Oct 2 13:56:39 2020,4
1,11,噓: 11,分數: 0,作者: LoveMakeLove (ボケ),標題: [新聞]江啟臣：兩岸是不對稱的戰爭 從募兵改徵兵,時間: Wed Oct 7 18:53:08 2020,11
2,20,噓: 0,分數: 20,作者: MintSu (Simon),標題: [問卦] 如果川普老婆死於武漢肺炎會怎麼樣？,時間: Fri Oct 2 13:30:55 2020,0
3,31,噓: 2,分數: 29,作者: seiya2000 (風見),標題: [問卦] 為什麼古代生物體型可以長到這麼大？,時間: Fri Oct 2 12:35:18 2020,2
4,106,噓: 6,分數: 100,作者: kasumi5566 (霞),標題: [問卦] 支那女生是不是都沒錢修補衣服,時間: Fri Oct 2 13:43:25 2020,6
...,...,...,...,...,...,...,...
833,10,噓: 1,分數: 9,作者: lockgolden (鎖金),標題: [問卦] PTT十年後會像無名小站那樣關閉嗎?,時間: Fri Oct 2 14:09:32 2020,1
834,7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020,0
835,0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020,0
836,15,噓: 4,分數: 11,作者: stan0720 (Kimo),標題: [問卦] 認真問 人一天可以走幾公里呀？,時間: Fri Oct 2 14:00:50 2020,4
837,5,噓: 0,分數: 5,作者: bigtreelife (Tree),標題: [問卦] 叫外送的年輕人都是什麼人,時間: Fri Oct 2 15:29:44 2020,0

In [16]:
pd.to_datetime("20260510")

Timestamp('2026-05-10 00:00:00')

In [17]:
pd.to_datetime("2026-05-10")

Timestamp('2026-05-10 00:00:00')

In [18]:
pd.to_datetime("2026/05/10")

Timestamp('2026-05-10 00:00:00')

In [20]:
pd.to_datetime("2026/05/10 10:30:44")

Timestamp('2026-05-10 10:30:44')

In [21]:
pd.to_datetime("2026-05-10T10:30:44")

Timestamp('2026-05-10 10:30:44')

In [22]:
"""Fri Oct  2 13:56:39 2020"""
pd.to_datetime("Fri Oct  2 13:56:39 2020")

Timestamp('2020-10-02 13:56:39')

In [24]:
df["時間"].str.split(":").str[1]

0       Fri Oct  2 13
1       Wed Oct  7 18
2       Fri Oct  2 13
3       Fri Oct  2 12
4       Fri Oct  2 13
            ...
833     Fri Oct  2 14
834     Wed Oct  7 21
835     Wed Oct  7 21
836     Fri Oct  2 14
837     Fri Oct  2 15
Name: 時間, Length: 838, dtype: object

In [25]:
df["時間"].str.split(":").str[1].apply(pd.to_datetime)

0     2013-10-02
1     2018-10-07
2     2013-10-02
3     2012-10-02
4     2013-10-02
         ...
833   2014-10-02
834   2021-10-07
835   2021-10-07
836   2014-10-02
837   2015-10-02
Name: 時間, Length: 838, dtype: datetime64[us]

In [26]:
pd.to_datetime(df["時間"].str.split(":").str[1])

/var/folders/_k/k5dry95j0q5d35_9pn5d86vm0000gn/T/ipykernel_77936/3856744943.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(df["時間"].str.split(":").str[1])

0     2013-10-02
1     2018-10-07
2     2013-10-02
3     2012-10-02
4     2013-10-02
         ...
833   2014-10-02
834   2021-10-07
835   2021-10-07
836   2014-10-02
837   2015-10-02
Name: 時間, Length: 838, dtype: datetime64[us]

In [ ]:
df["時間"].apply(
    lambda x: pd.to_datetime(
        x.split(":")[1].strip(),
    )
)

0     2013-10-02
1     2018-10-07
2     2013-10-02
3     2012-10-02
4     2013-10-02
         ...
833   2014-10-02
834   2021-10-07
835   2021-10-07
836   2014-10-02
837   2015-10-02
Name: 時間, Length: 838, dtype: datetime64[us]

In [28]:
df["時間"].apply(
    lambda x: pd.to_datetime(
        x.split(":")[1].strip(),
    )
) >= pd.to_datetime("2021-10-01")

0      False
1      False
2      False
3      False
4      False
       ...
833    False
834     True
835     True
836    False
837    False
Name: 時間, Length: 838, dtype: bool

In [31]:
df[
    df["時間"].apply(
        lambda x: pd.to_datetime(
            x.split(":")[1].strip(),
        )
    ) >= "2022-10-01"
]

,推,噓,分數,作者,標題,時間,噓_t
216,990,噓: 66,分數: 924,作者: ubcs (覺★青年超冒險蓋),標題: [公告] 中秋連假線上烤肉兼置底聯誼閒聊區,時間: Wed Sep 30 23:45:49 2020,66

In [33]:
df["時間_t"] = df["時間"].apply(
        lambda x: pd.to_datetime(
            x.split(":")[1].strip(),
        )
    )
df

,推,噓,分數,作者,標題,時間,噓_t,時間_t
0,25,噓: 4,分數: 21,作者: Rusnake5566 (魯蛇+56 PTT最強帳號),標題: [問卦] 兩個候選人選前一個月同時陣亡的可能性,時間: Fri Oct 2 13:56:39 2020,4,2013-10-02
1,11,噓: 11,分數: 0,作者: LoveMakeLove (ボケ),標題: [新聞]江啟臣：兩岸是不對稱的戰爭 從募兵改徵兵,時間: Wed Oct 7 18:53:08 2020,11,2018-10-07
2,20,噓: 0,分數: 20,作者: MintSu (Simon),標題: [問卦] 如果川普老婆死於武漢肺炎會怎麼樣？,時間: Fri Oct 2 13:30:55 2020,0,2013-10-02
3,31,噓: 2,分數: 29,作者: seiya2000 (風見),標題: [問卦] 為什麼古代生物體型可以長到這麼大？,時間: Fri Oct 2 12:35:18 2020,2,2012-10-02
4,106,噓: 6,分數: 100,作者: kasumi5566 (霞),標題: [問卦] 支那女生是不是都沒錢修補衣服,時間: Fri Oct 2 13:43:25 2020,6,2013-10-02
...,...,...,...,...,...,...,...,...
833,10,噓: 1,分數: 9,作者: lockgolden (鎖金),標題: [問卦] PTT十年後會像無名小站那樣關閉嗎?,時間: Fri Oct 2 14:09:32 2020,1,2014-10-02
834,7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020,0,2021-10-07
835,0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020,0,2021-10-07
836,15,噓: 4,分數: 11,作者: stan0720 (Kimo),標題: [問卦] 認真問 人一天可以走幾公里呀？,時間: Fri Oct 2 14:00:50 2020,4,2014-10-02
837,5,噓: 0,分數: 5,作者: bigtreelife (Tree),標題: [問卦] 叫外送的年輕人都是什麼人,時間: Fri Oct 2 15:29:44 2020,0,2015-10-02

In [34]:
df[
    df["時間_t"] > "2021-10-01"
]

,推,噓,分數,作者,標題,時間,噓_t,時間_t
28,2,噓: 2,分數: 0,作者: jiouje (JioUje),標題: [問卦] 洗頭妹 幫我洗頭帶手套？？？？,時間: Wed Oct 7 21:20:19 2020,2,2021-10-07
33,4,噓: 0,分數: 4,作者: hmt17 (Popo:(bﾟ▽ﾟ)b),標題: [新聞]《惡靈古堡》電影再啟卡司曝光！Netfix影,時間: Wed Oct 7 21:20:51 2020,0,2021-10-07
62,0,噓: 2,分數: -2,作者: d995511 (flcl),標題: [問卦] 買惹many發現路上妹子都在看我怎麼辦？,時間: Wed Oct 7 21:23:36 2020,2,2021-10-07
86,10,噓: 5,分數: 5,作者: stockeye (stockeye),標題: [新聞] 救豬農「百億基金」首曝光 陳吉仲：4年共,時間: Wed Oct 7 21:00:08 2020,5,2021-10-07
95,3,噓: 0,分數: 3,作者: jun059 (好想睡覺),標題: [問卦] 想見你為啥沒入圍金曲獎？,時間: Wed Oct 7 21:15:44 2020,0,2021-10-07
163,2,噓: 0,分數: 2,作者: shala (沙羅是轉換後的文字檔打m),標題: [問卦] 開戰後要打多久才能讓共匪喪失戰意？,時間: Wed Oct 7 21:03:18 2020,0,2021-10-07
180,6,噓: 4,分數: 2,作者: kuro (垃圾不分藍綠),標題: [新聞] 台灣大道違停昨害死18歲女大生 扯！貨車,時間: Wed Oct 7 21:10:17 2020,4,2021-10-07
216,990,噓: 66,分數: 924,作者: ubcs (覺★青年超冒險蓋),標題: [公告] 中秋連假線上烤肉兼置底聯誼閒聊區,時間: Wed Sep 30 23:45:49 2020,66,2023-09-30
219,3,噓: 0,分數: 3,作者: jason851124 (YeeeEX),標題: [問卦] 台灣情趣用品店怎麼那麼多？,時間: Wed Oct 7 21:25:53 2020,0,2021-10-07
260,7,噓: 3,分數: 4,作者: LineageM (天堂M),標題: [問卦] 隔壁女鄰居來借幾包麵？該借嗎,時間: Wed Oct 7 21:09:56 2020,3,2021-10-07
299,1,噓: 1,分數: 0,作者: en5151 (asenen),標題: [問卦] 如果立法院拍youtobe開頻道有搞頭嗎？,時間: Wed Oct 7 21:07:32 2020,1,2021-10-07
324,0,噓: 4,分數: -4,作者: cowboyas0413 (RAID0一時爽 資料火葬場),標題: [問卦] 對不起我騙了妳,時間: Wed Oct 7 21:25:42 2020,4,2021-10-07
328,1,噓: 2,分數: -1,作者: LoveMakeLove (ボケ),標題: [問卦] 乾脆抓監獄重刑犯和8+9充軍不就好了？,時間: Wed Oct 7 21:09:46 2020,2,2021-10-07
368,5,噓: 5,分數: 0,作者: ai770116 (東方的神秘力量),標題: [問卦] 川普超沒水準都不戴口罩PTT還挺川普？,時間: Wed Oct 7 21:25:21 2020,5,2021-10-07
371,0,噓: 0,分數: 0,作者: llgod (Wryyyyyyyy),標題: [問卦] 噁茫啊斯是不是超好玩超心機,時間: Wed Oct 7 21:27:58 2020,0,2021-10-07
375,1,噓: 0,分數: 1,作者: a15661263 (誠實豆沙包),標題: [問卦] SONY新世代手機是不是總是缺了點什麼??,時間: Wed Oct 7 21:14:54 2020,0,2021-10-07
377,2,噓: 0,分數: 2,作者: qazxc1156892 (QQ),標題: [問卦] 美國總統民調到底要贏多少%才算穩?,時間: Wed Oct 7 21:27:23 2020,0,2021-10-07
389,8,噓: 3,分數: 5,作者: genheit (genheit),標題: [問卦] 當時蜀國怎麼不南下取緬甸、泰國？,時間: Wed Oct 7 21:07:10 2020,3,2021-10-07
400,17,噓: 8,分數: 9,作者: dzwei (Args&&... args),標題: [問卦] 李永樂老師屌打台灣多數的Youtuber吧?,時間: Wed Oct 7 21:03:52 2020,8,2021-10-07
419,1,噓: 4,分數: -3,作者: ILoveMegumin (白上吹雪的刻印蟲),標題: [問卦] 日本的鐵路比台灣進步很多,時間: Wed Oct 7 21:21:20 2020,4,2021-10-07
442,10,噓: 9,分數: 1,作者: cheerbu (buchi),標題: [新聞] 遭柯文哲批「說謊」 王世堅反嗆：liar憑,時間: Wed Oct 7 21:11:56 2020,9,2021-10-07
449,0,噓: 0,分數: 0,作者: PrinceKanto (生田絵梨花は俺の嫁),"標題: [問卦] 乃木坂""夏のFree&Easy""ＭＶ的觀看重點?",時間: Wed Oct 7 21:34:09 2020,0,2021-10-07
452,11,噓: 1,分數: 10,作者: heavenlyken (銀狐),標題: [問卦] 為什麼日本超商很多外國店員但台灣沒有？,時間: Wed Oct 7 21:03:54 2020,1,2021-10-07
457,36,噓: 1,分數: 35,作者: b10485762000 (台北寂寞部屋),標題: [新聞] 魔音洗腦！美獄警逼受刑人聽2小時「Baby,時間: Wed Oct 7 21:12:38 2020,1,2021-10-07
462,0,噓: 0,分數: 0,作者: norgthas (norgthas),標題: [問卦]關於適應極端氣候的問題 醫森醫學系生請進,時間: Wed Oct 7 21:32:04 2020,0,2021-10-07
470,8,噓: 2,分數: 6,作者: yhltyy (大堡礁),標題: [問卦] 無事不登三寶殿 是哪三寶,時間: Wed Oct 7 21:07:53 2020,2,2021-10-07
476,32,噓: 14,分數: 18,作者: autoimmune (..),標題: [新聞] 藍喊台美復交 陳柏惟：可跟中國建交,時間: Wed Oct 7 21:23:38 2020,14,2021-10-07
499,22,噓: 1,分數: 21,作者: Francise (少喝飲料多喝水),標題: [新聞] 竹聯幫內訌！萬華大亂鬥砍死人 賭場利,時間: Wed Oct 7 21:26:36 2020,1,2021-10-07
509,5,噓: 1,分數: 4,作者: Rrrxddd (有噴蛤蜊 RR),標題: [問卦] 是誰發現 香蕉 可以吃的,時間: Wed Oct 7 21:05:22 2020,1,2021-10-07
518,7,噓: 3,分數: 4,作者: Lucky0105 (洋),標題: [問卦] 流氓能買的起c300？賺錢能力超強？,時間: Wed Oct 7 21:03:21 2020,3,2021-10-07
575,0,噓: 0,分數: 0,作者: semih (Sayginer),標題: [新聞] 桃園砸1950萬元辦萬聖節觀光活動 民代批,時間: Wed Oct 7 21:29:43 2020,0,2021-10-07
581,4,噓: 3,分數: 1,作者: aynmeow (我想成為安康魚),標題: [問卦] 我朋友打雪仗害死同事,時間: Wed Oct 7 21:14:56 2020,3,2021-10-07
585,0,噓: 0,分數: 0,作者: echoo (回聲O),標題: [問卦] 澎湖的街景怎麼能那麼乾淨,時間: Wed Oct 7 21:33:13 2020,0,2021-10-07
607,4,噓: 1,分數: 3,作者: Starcraft3 (小藥丸),標題: [新聞] 又出包!實名制口罩僅2層沒有熔噴不織布,時間: Wed Oct 7 21:10:09 2020,1,2021-10-07
609,19,噓: 2,分數: 17,作者: andy199113 (Andy),標題: [新聞] 男拾獲疑「龍涎香」石頭 鑑定結果出爐「,時間: Wed Oct 7 21:10:34 2020,2,2021-10-07
614,46,噓: 2,分數: 44,作者: ak47box (陽光黃金蛋),標題: [新聞] 高市國小冷氣跳電停機1個月！網讚柯文哲,時間: Wed Oct 7 21:06:33 2020,2,2021-10-07
618,2,噓: 4,分數: -2,作者: s37166117 (ace),標題: [問卦] 嘴唇乾裂怎麼辦,時間: Wed Oct 7 21:05:30 2020,4,2021-10-07
631,3,噓: 6,分數: -3,作者: cake10414 (Peter),標題: [新聞] 台南黃金海岸淪垃圾海岸 中國媒體諷：這,時間: Wed Oct 7 21:18:40 2020,6,2021-10-07
637,6,噓: 1,分數: 5,作者: pl132 (pl132),標題: [新聞]四方安全對話 印度自信滿滿：空軍已經隨,時間: Wed Oct 7 21:10:35 2020,1,2021-10-07
684,1,噓: 1,分數: 0,作者: algebraic (algebraic),標題: [問卦] 可以帶十八禁抱枕去宿舍嗎?,時間: Wed Oct 7 21:03:14 2020,1,2021-10-07
688,19,噓: 1,分數: 18,作者: KouKouMeow (摳摳),標題: [協尋] 高雄前金區 黑白貓小蜜(代po),時間: Wed Sep 30 22:46:26 2020,1,2022-09-30
711,1,噓: 3,分數: -2,作者: Gary5566 (等我長大要娶天音かなた),標題: [問卦] 下課想直接回家卻被我姊叫去加社團,時間: Wed Oct 7 21:17:44 2020,3,2021-10-07
714,19,噓: 5,分數: 14,作者: seabox (盒盒),標題: [公告] 數條板規修改草案於gossippicket討論,時間: Sun Oct 4 21:16:27 2020,5,2021-10-04
754,12,噓: 1,分數: 11,作者: saiulbb (#KEEP MLB GREAT!),標題: [新聞] 「你幾歲開始長陰毛？」 丹麥兒童節目給,時間: Wed Oct 7 21:21:10 2020,1,2021-10-07
766,4,噓: 0,分數: 4,作者: iamshana (CANINE力集中在一些重要S),標題: [新聞] 台鐵區間車撞到闖入機車 保安=中洲雙向,時間: Wed Oct 7 21:17:49 2020,0,2021-10-07
767,2,噓: 2,分數: 0,作者: Comebuy (三分鐘熱度),標題: [新聞] 違國際禁令偷賣北韓石油3000噸 貪財船東,時間: Wed Oct 7 21:16:21 2020,2,2021-10-07
774,10,噓: 1,分數: 9,作者: AllMight (澤近愛理我老婆),標題: [問卦] 白石到底有什麼資格站在西野七瀬旁邊？,時間: Wed Oct 7 21:07:42 2020,1,2021-10-07
775,2,噓: 0,分數: 2,作者: qazxc1156892 (QQ),標題: [問卦] 侯昌明的代表作是什麼?,時間: Wed Oct 7 21:33:51 2020,0,2021-10-07
777,6,噓: 3,分數: 3,作者: toto3527 (toto),標題: [問卦] 我破解兩岸開戰的方法了,時間: Wed Oct 7 21:03:07 2020,3,2021-10-07
795,2,噓: 5,分數: -3,作者: Fortran (Fortran),標題: [問卦] 墾丁後壁湖海底十字架的八卦,時間: Wed Oct 7 21:23:52 2020,5,2021-10-07
805,7,噓: 2,分數: 5,作者: chadmu (查德姆),標題: [問卦] 在全聯上班是什麼感覺,時間: Wed Oct 7 21:21:50 2020,2,2021-10-07
821,0,噓: 0,分數: 0,作者: Assisi (Francesco d'Assisi),標題: [問卦] 張鋒現在在想蛇摸ㄋ ?? ☺ ☺ ☺ ☺ ☺,時間: Wed Oct 7 21:28:32 2020,0,2021-10-07
834,7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020,0,2021-10-07
835,0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020,0,2021-10-07

In [39]:
pd.to_datetime("Wed Oct  7 21:20:19 2020")

Timestamp('2020-10-07 21:20:19')

In [40]:
"%a %b %d %H:%M:%S %Y"
pd.to_datetime("Wed Oct  7 21:20:19 2020", format="%a %b %d %H:%M:%S %Y")

Timestamp('2020-10-07 21:20:19')

In [38]:
df[
    df["時間"].apply(
        lambda x: pd.to_datetime(
            x.split(":")[1].strip(),
            format="%a %b %d %H:%M:%S %Y",
        )
    ) >= "2022-10-01"
]

ValueError: time data "Fri Oct  2 13" doesn't match format "%a %b %d %H:%M:%S %Y". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.