In [1]:
import pandas as pd

df = pd.read_csv("employees.csv")
df

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White          NaN  68000.0  carol.white@company.com
3        E004          NaN          NaN  55000.0                      NaN
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com
5        E006          NaN          NaN      NaN                      NaN

In [3]:
type(None)

NoneType

In [5]:
type(df["name"][5])

float

In [6]:
import numpy as np

np.nan

nan

In [8]:
df

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White          NaN  68000.0  carol.white@company.com
3        E004          NaN          NaN  55000.0                      NaN
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com
5        E006          NaN          NaN      NaN                      NaN

In [7]:
df["salary"].sum()

np.float64(290000.0)

In [9]:
df["salary"].mean()

np.float64(72500.0)

In [10]:
290000.0 / 4

72500.0

In [11]:
df["salary"].fillna(0)

0    95000.0
1    72000.0
2    68000.0
3    55000.0
4        0.0
5        0.0
Name: salary, dtype: float64

In [12]:
df

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White          NaN  68000.0  carol.white@company.com
3        E004          NaN          NaN  55000.0                      NaN
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com
5        E006          NaN          NaN      NaN                      NaN

In [13]:
df["department"].fillna("part-time")

0    Engineering
1      Marketing
2      part-time
3      part-time
4          Sales
5      part-time
Name: department, dtype: str

In [14]:
df.isna()

   employee_id   name  department  salary  email
0        False  False       False   False  False
1        False  False       False   False   True
2        False  False        True   False  False
3        False   True        True   False   True
4        False  False       False    True  False
5        False   True        True    True   True

In [15]:
df[df.isna()]

  employee_id name department  salary email
0         NaN  NaN        NaN     NaN   NaN
1         NaN  NaN        NaN     NaN   NaN
2         NaN  NaN        NaN     NaN   NaN
3         NaN  NaN        NaN     NaN   NaN
4         NaN  NaN        NaN     NaN   NaN
5         NaN  NaN        NaN     NaN   NaN

In [16]:
df["department"].isna()

0    False
1    False
2     True
3     True
4    False
5     True
Name: department, dtype: bool

In [17]:
df[df["department"].isna()]

  employee_id         name department   salary                    email
2        E003  Carol White        NaN  68000.0  carol.white@company.com
3        E004          NaN        NaN  55000.0                      NaN
5        E006          NaN        NaN      NaN                      NaN

In [18]:
df[~df["department"].isna()]

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com

In [19]:
df["department"].notna()

0     True
1     True
2    False
3    False
4     True
5    False
Name: department, dtype: bool

In [28]:
df[df["department"].notna()]

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com

In [20]:
df["department"].isnull()

0    False
1    False
2     True
3     True
4    False
5     True
Name: department, dtype: bool

In [22]:
df

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White          NaN  68000.0  carol.white@company.com
3        E004          NaN          NaN  55000.0                      NaN
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com
5        E006          NaN          NaN      NaN                      NaN

In [21]:
df.dropna()

  employee_id        name   department   salary                   email
0        E001  Alice Chen  Engineering  95000.0  alice.chen@company.com

In [24]:
df.dropna(thresh=2)

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White          NaN  68000.0  carol.white@company.com
3        E004          NaN          NaN  55000.0                      NaN
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com

In [25]:
df

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White          NaN  68000.0  carol.white@company.com
3        E004          NaN          NaN  55000.0                      NaN
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com
5        E006          NaN          NaN      NaN                      NaN

In [27]:
df["department"].ffill()

0    Engineering
1      Marketing
2      Marketing
3      Marketing
4          Sales
5          Sales
Name: department, dtype: str