In [2]:
import pandas as pd
from pandasql import sqldf

path_staff = "staff.csv"
path_staff_detail = "staff_detail.csv"
path_staff_detail_different_col = "staff_detail_different_col.csv"
path_staff_samecol = "staff_samecol.csv"

df_path_staff = pd.read_csv(path_staff)
df_path_staff_detail = pd.read_csv(path_staff_detail)
df_path_staff_detail_different_col = pd.read_csv(path_staff_detail_different_col)
df_path_staff_samecol = pd.read_csv(path_staff_samecol)

In [3]:
sql = """
select * from df_path_staff
"""
sqldf(sql)

   ID   Name  DeptId  Age Gender  Salary
0   1   Mike       2   45      M   60000
1   2   Judy       2   30      F   48000
2   3  Allen       1   22      M   50000
3   4    Tom       2   47      M   47000
4   5   Jack       3   36      M   52000
5   6   Abby       2   24      F   45000
6   7  Trump       1   80      M   80000
7   8  Marry       3   29      F   87000

In [6]:
sql = """
select
    detail.ID as empID,
    Level,
    Name,
    Salary
from df_path_staff_detail detail
left join df_path_staff staff
on detail.ID = staff.ID
"""
sqldf(sql)

    empID Level   Name  Salary
0       1     A   Mike   60000
1       1     S   Mike   60000
2       2     A   Judy   48000
3       3     A  Allen   50000
4       3     S  Allen   50000
5       4     A    Tom   47000
6       5     A   Jack   52000
7       5     S   Jack   52000
8       6     A   Abby   45000
9       7     A  Trump   80000
10      7     S  Trump   80000
11      7     M  Trump   80000
12      8     A  Marry   87000
13      8     S  Marry   87000
14      8     M  Marry   87000

In [8]:
globals()["df_path_staff"]

   ID   Name  DeptId  Age Gender  Salary
0   1   Mike       2   45      M   60000
1   2   Judy       2   30      F   48000
2   3  Allen       1   22      M   50000
3   4    Tom       2   47      M   47000
4   5   Jack       3   36      M   52000
5   6   Abby       2   24      F   45000
6   7  Trump       1   80      M   80000
7   8  Marry       3   29      F   87000